apiVersion: v1
kind: List
items:
- apiVersion: "v1"
  kind: "Secret"
  metadata:
    name: "aws-s3-secret"
  data:
    # don't forget to base64 encode your values
    aws-access-key-id: ""
    aws-secret-access-key: ""
- apiVersion: "v1"
  kind: "Secret"
  metadata:
    name: "openssl-encryption-secret"
  data:
    # don't forget to base64 encode your values
    encryption-pass-phrase: ""
- apiVersion: "v1"
  kind: "Secret"
  metadata:
    name: "smtp-authentication-secret-production"
  data:
    # don't forget to base64 encode your values
    smtp-user: ""
    smtp-password: ""
- apiVersion: batch/v2alpha1
  kind: ScheduledJob
  metadata:
    name: postgresql-s3-hourly-backup
  spec:
    # every start of the hour
    schedule: "0 * * * *"
    jobTemplate:
      spec:
        template:
          spec:
            # 30 minutes timeout
            activeDeadlineSeconds: 1800
            restartPolicy: OnFailure
            containers:
            - name: postgresql-s3-hourly-backup
              image: willemvd/postgresql-client-side-encrypted-s3-backup:1.1.0
              env:
              - name: PGDATABASE
                value:
              - name: PGHOST
                value:
              - name: PGPORT
                value: "5432"
              - name: PGUSER
                value:
              - name: PGPASSWORD
                value:
              - name: ENCRYPTION_PASS_PHRASE
                valueFrom:
                  secretKeyRef:
                    name: openssl-encryption-secret
                    key: encryption-pass-phrase
              - name: OPENSSL_CIPHER_TYPE
                value: aes-256-cbc
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: aws-s3-secret
                    key: aws-access-key-id
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: aws-s3-secret
                    key: aws-secret-access-key
              - name: AWS_DEFAULT_REGION
                value:
              - name: S3_BUCKET_NAME
                value:
              - name: BACKUP_TYPE
                value: hourly
              - name: ENABLE_ERROR_MAIL
                value: "true"
              - name: ERROR_MAIL_SUBJECT
                value: Failed to run database backup
              - name: SMTP_HOST
                value: ""
              - name: SMTP_PORT
                value: ""
              - name: SMTP_STARTTLS
                value: "true"
              - name: SMTP_AUTH
                value:
              - name: SMTP_AUTH_USER
                valueFrom:
                  secretKeyRef:
                    name: smtp-authentication-secret-production
                    key: smtp-user
              - name: SMTP_AUTH_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: smtp-authentication-secret-production
                    key: smtp-password
              - name: SMTP_FROM
                value: ""
              - name: SMTP_TO
                value: ""
              - name: ALWAYS_EXIT_ZERO
                value: "true"
- apiVersion: batch/v2alpha1
  kind: ScheduledJob
  metadata:
    name: postgresql-s3-daily-backup
  spec:
    # daily at 02:30 (do not run at the whole hour to prevent potential issues with hourly run)
    schedule: "30 2 * * *"
    jobTemplate:
      spec:
        template:
          spec:
            # 30 minutes timeout
            activeDeadlineSeconds: 1800
            restartPolicy: OnFailure
            containers:
            - name: postgresql-s3-daily-backup
              image: willemvd/postgresql-client-side-encrypted-s3-backup:1.1.0
              env:
              - name: PGDATABASE
                value:
              - name: PGHOST
                value:
              - name: PGPORT
                value: "5432"
              - name: PGUSER
                value:
              - name: PGPASSWORD
                value:
              - name: ENCRYPTION_PASS_PHRASE
                valueFrom:
                  secretKeyRef:
                    name: openssl-encryption-secret
                    key: encryption-pass-phrase
              - name: OPENSSL_CIPHER_TYPE
                value: aes-256-cbc
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: aws-s3-secret
                    key: aws-access-key-id
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: aws-s3-secret
                    key: aws-secret-access-key
              - name: AWS_DEFAULT_REGION
                value:
              - name: S3_BUCKET_NAME
                value:
              - name: BACKUP_TYPE
                value: daily
              - name: ENABLE_ERROR_MAIL
                value: "true"
              - name: ERROR_MAIL_SUBJECT
                value: Failed to run database backup
              - name: SMTP_HOST
                value: ""
              - name: SMTP_PORT
                value: ""
              - name: SMTP_STARTTLS
                value: "true"
              - name: SMTP_AUTH
                value:
              - name: SMTP_AUTH_USER
                valueFrom:
                  secretKeyRef:
                    name: smtp-authentication-secret-production
                    key: smtp-user
              - name: SMTP_AUTH_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: smtp-authentication-secret-production
                    key: smtp-password
              - name: SMTP_FROM
                value: ""
              - name: SMTP_TO
                value: ""
              - name: ALWAYS_EXIT_ZERO
                value: "true"